# SPDX-License-Identifier: GPL-2.0-or-later
name: cherrytree
adopt-info: cherrytree
summary: Hierarchical note taking application
description: |
  A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single XML or SQLite file. The project home page is giuspen.net/cherrytree.

grade: stable
confinement: strict
base: core22
compression: lzo

slots:
  cherrytree-dbus:
    interface: dbus
    bus: session
    name: net.giuspen.cherrytree

plugs:
  dot-config-cherrytree:
    interface: personal-files
    write: [ $HOME/.config/cherrytree ]
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

assumes: [ command-chain ]

parts:
  cherrytree:
    plugin: cmake
    source-type: git
    source: https://github.com/giuspen/cherrytree.git
    source-commit: c7e738dff3e7567cb6f711cc4b8b31ad290084ce
    source-depth: 0
    cmake-parameters:
      - '-DCMAKE_INSTALL_PREFIX='
      - '-DBUILD_TESTING='
      - '-DSNAP_OPT_PRE_CMAKE_INSTALL_PREFIX=/snap/cherrytree/current'
    build-packages:
      - build-essential
      - cmake
      - pkg-config
      - libgtkmm-3.0-dev
      - libgtksourceviewmm-3.0-dev
      - libxml++2.6-dev
      - libsqlite3-dev
      - gettext
      - libgspell-1-dev
      - libcurl4-openssl-dev
      - libuchardet-dev
      - libfribidi-dev
      - libfmt-dev
      - libspdlog-dev
    stage-packages:
      - libgtkmm-3.0-1v5
      - libgtksourceviewmm-3.0-0v5
      - libxml++2.6-2v5
      - libsqlite3-0
      - libgspell-1-2
      - libcurl4
      - libuchardet0
      - libfribidi0
      - libspdlog1
      - texlive-latex-base
      - dvipng
    prime:
      - -lib/cherrytree/*.a
      - -*canberra*so* # We don't have sound permissions anyway
      - -usr/lib/*/gtk-2.0
    override-build: |
      sed -i 's|^Icon=.*|Icon=${SNAP}/share/icons/hicolor/scalable/apps/cherrytree.svg|' ${SNAPCRAFT_PART_SRC}/data/cherrytree.desktop
      snapcraftctl build
    parse-info: [ share/metainfo/net.giuspen.cherrytree.metainfo.xml ]
  desktop-helpers:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - libgtk-3-dev
      - locales
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - fonts-ubuntu
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgtk-3-bin
      - libglib2.0-bin
      - locales-all
      - libc-bin
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3
      - librsvg2-common # SVG pixbuf loader
    prime:
      - -*canberra*so* # We don't have sound permissions anyway
      - -usr/lib/*/gtk-2.0
    override-prime: |
      snapcraftctl prime
      glib-compile-schemas ${SNAPCRAFT_PRIME}/usr/share/glib-2.0/schemas/
      LOCPATH=${SNAPCRAFT_PRIME}/usr/lib/locale locale-gen
    after: [cherrytree] # Last so we compile all the schemas
  gtk-locales:
    plugin: nil
    override-pull: |
      set -eux
      apt-get download "language-pack-*-base"
    override-build: |
      set -eux
      for deb in *.deb; do dpkg-deb -x $deb .; done
      find usr/share/locale-langpack -type f -not -name "gtk30*.mo" -and -not -name "glib*.mo" -and -not -name "gdk*.mo" -and -not -name "gspell*.mo" -delete
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share
      cp -r usr/share/locale-langpack $SNAPCRAFT_PART_INSTALL/usr/share/

apps:
  cherrytree:
    command: bin/cherrytree
    command-chain: [ bin/desktop-launch ]
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - wayland
      - x11
      - unity7
      - dot-config-cherrytree
      - removable-media
      - network
    slots:
      - cherrytree-dbus
    desktop: share/applications/cherrytree.desktop
    common-id: net.giuspen.cherrytree

hooks:
  configure:
    plugs:
      - desktop
